# Generated by Django 5.0.4 on 2024-04-30 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("breast", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(name="customuser", managers=[],),
    ]
