# Generated by Django 5.0.4 on 2024-05-04 17:05

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("breast", "0002_alter_customuser_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[("objects", django.contrib.auth.models.UserManager()),],
        ),
    ]
