# Generated by Django 5.0.4 on 2024-05-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("breast", "0003_alter_customuser_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="middle_name",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
