# Generated by Django 5.0.4 on 2024-06-24 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("breast", "0005_doctor_visit"),
    ]

    operations = [
        migrations.RemoveField(model_name="visit", name="doctor",),
        migrations.DeleteModel(name="Doctor",),
        migrations.DeleteModel(name="Visit",),
    ]
