# Generated by Django 5.0.4 on 2024-08-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("breast", "0007_patient_date_radiologistcomment"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doctor", models.CharField(max_length=100)),
                ("visit_date", models.DateField()),
                ("patient", models.CharField(max_length=100)),
                ("patient_id", models.CharField(max_length=50)),
                ("age", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=6
                    ),
                ),
                ("assessment", models.TextField()),
            ],
        ),
    ]
