# Generated by Django 5.0.4 on 2024-08-05 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("breast", "0008_medicalreport"),
    ]

    operations = [
        migrations.RemoveField(model_name="medicalreport", name="age",),
        migrations.RemoveField(model_name="medicalreport", name="gender",),
        migrations.RemoveField(model_name="medicalreport", name="patient_id",),
        migrations.AlterField(
            model_name="medicalreport",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="medicalreport",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="breast.patient"
            ),
        ),
    ]
